#!/usr/bin/env bats
# Unit tests for tests/hooks/codify_learnings.py - extracts Codified-Learning
# trailers from a merged PR's commits and appends entries to design/lessons.md.
# shellcheck disable=SC2154
bats_require_minimum_version 1.5.0

REPO_SRC="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"

setup() {
  TMP="$(mktemp -d)"
  LESSONS="$TMP/lessons.md"
  PR_JSON="$TMP/pr.json"

  # Minimal lessons.md fixture: index region + L-000 seed.
  cat >"$LESSONS" <<'EOF'
# Test Lessons

## Tag index

<!-- AUTO-GENERATED by codify_learnings.py - do not edit by hand -->
<!-- Tags populate as entries land via the post-merge workflow -->

_(none yet - first entry will land here after the first PR with a `Codified-Learning:` trailer merges)_

<!-- /AUTO-GENERATED -->

## Entries

## L-000 - 2026-05-23 - meta

**Source:** seed

L-000 is the seed entry.

---
EOF
}

teardown() {
  rm -rf "$TMP"
}

_run_codify() {
  local pr="$1" sha="$2"
  cd "$REPO_SRC" || return
  python3 -m tests.hooks.codify_learnings \
    --pr "$pr" --merge-sha "$sha" \
    --lessons-md "$LESSONS" --input "$PR_JSON"
}

@test "no commits => no-op, exit 0, no file change" {
  echo '{"commits": [], "mergeCommit": {"oid": "deadbee"}}' >"$PR_JSON"
  before="$(cat "$LESSONS")"
  run _run_codify 42 deadbeef1234567
  [[ "$status" -eq 0 ]]
  [[ "$(cat "$LESSONS")" == "$before" ]]
}

@test "commits without trailers => no-op" {
  cat >"$PR_JSON" <<'EOF'
{"commits":[{"messageBody":"fix(x): just a typo"}],"mergeCommit":{"oid":"deadbeef1234567"}}
EOF
  before="$(cat "$LESSONS")"
  run _run_codify 42 deadbeef1234567
  [[ "$status" -eq 0 ]]
  [[ "$(cat "$LESSONS")" == "$before" ]]
}

@test "one untagged trailer => appends L-001 with tag 'general'" {
  cat >"$PR_JSON" <<'EOF'
{"commits":[{"messageBody":"fix(x): something\n\nCodified-Learning: A general lesson."}],"mergeCommit":{"oid":"deadbeef1234567"}}
EOF
  run _run_codify 42 deadbeef1234567
  [[ "$status" -eq 0 ]]
  [[ "$output" == "L-001" ]]
  grep -q '^## L-001 - .* - general$' "$LESSONS"
  grep -q 'PR #42 (`deadbee`)' "$LESSONS"
  grep -q 'A general lesson.' "$LESSONS"
}

@test "tagged trailer => appends with that tag" {
  cat >"$PR_JSON" <<'EOF'
{"commits":[{"messageBody":"fix(x): something\n\nCodified-Learning(do-not-repeat): A specific rule."}],"mergeCommit":{"oid":"deadbeef1234567"}}
EOF
  run _run_codify 7 deadbeef1234567
  [[ "$status" -eq 0 ]]
  [[ "$output" == "L-001" ]]
  grep -q '^## L-001 - .* - do-not-repeat$' "$LESSONS"
}

@test "multiple trailers across commits => sequential IDs, range printed" {
  cat >"$PR_JSON" <<'EOF'
{"commits":[
  {"messageBody":"a\n\nCodified-Learning: First lesson."},
  {"messageBody":"b\n\nCodified-Learning(conv): Second lesson."},
  {"messageBody":"c\n\nCodified-Learning: Third lesson."}
],"mergeCommit":{"oid":"deadbeef1234567"}}
EOF
  run _run_codify 42 deadbeef1234567
  [[ "$status" -eq 0 ]]
  [[ "$output" == "L-001-L-003" ]]
  grep -q '^## L-001 - .* - general$' "$LESSONS"
  grep -q '^## L-002 - .* - conv$' "$LESSONS"
  grep -q '^## L-003 - .* - general$' "$LESSONS"
}

@test "respects existing L-NNN entries; next ID continues from max+1" {
  # Pre-populate with L-005 so the next entry should be L-006.
  cat >>"$LESSONS" <<'EOF'

## L-005 - 2026-05-22 - prior

**Source:** PR #99 (`abc1234`)

A prior entry.

---
EOF
  cat >"$PR_JSON" <<'EOF'
{"commits":[{"messageBody":"x\n\nCodified-Learning: new lesson."}],"mergeCommit":{"oid":"deadbeef1234567"}}
EOF
  run _run_codify 100 deadbeef1234567
  [[ "$status" -eq 0 ]]
  [[ "$output" == "L-006" ]]
  grep -q '^## L-006 - .* - general$' "$LESSONS"
}

@test "index regenerated and groups by tag" {
  cat >"$PR_JSON" <<'EOF'
{"commits":[
  {"messageBody":"a\n\nCodified-Learning(alpha): A1."},
  {"messageBody":"b\n\nCodified-Learning(beta): B1."},
  {"messageBody":"c\n\nCodified-Learning(alpha): A2."}
],"mergeCommit":{"oid":"deadbeef1234567"}}
EOF
  run _run_codify 42 deadbeef1234567
  [[ "$status" -eq 0 ]]
  # Index should list both tags with their IDs.
  grep -q '\*\*alpha\*\* - .*L-001.*L-003' "$LESSONS"
  grep -q '\*\*beta\*\* - .*L-002' "$LESSONS"
  # Tags sorted alphabetically (alpha before beta).
  alpha_line=$(grep -n '^- \*\*alpha\*\*' "$LESSONS" | cut -d: -f1)
  beta_line=$(grep -n '^- \*\*beta\*\*' "$LESSONS" | cut -d: -f1)
  [[ "$alpha_line" -lt "$beta_line" ]]
}

@test "index anchors match GitHub's heading-slug format (date + tag included)" {
  # Regression test for the truncated `#l-NNN---` anchor bug: GitHub's slug for
  # a heading like `## L-001 - 2026-05-23 - alpha` is
  # `#l-001---2026-05-23---alpha`, not `#l-001---`. The truncated form does
  # not resolve, silently breaking the index every time it regenerates.
  cat >"$PR_JSON" <<'EOF'
{"commits":[{"messageBody":"x\n\nCodified-Learning(alpha): A1."}],"mergeCommit":{"oid":"deadbeef1234567"}}
EOF
  run _run_codify 42 deadbeef1234567
  [[ "$status" -eq 0 ]]
  # The seed L-000 (tag 'meta', date 2026-05-23) must keep its full-slug anchor.
  grep -qE '\[L-000\]\(#l-000---2026-05-23---meta\)' "$LESSONS"
  # The freshly-codified L-001 anchor must include today's date + tag.
  grep -qE '\[L-001\]\(#l-001---[0-9]{4}-[0-9]{2}-[0-9]{2}---alpha\)' "$LESSONS"
}

@test "trailer with continuation line not captured (single-line only for v1)" {
  cat >"$PR_JSON" <<'EOF'
{"commits":[{"messageBody":"x\n\nCodified-Learning: First line only.\n  continuation should be ignored."}],"mergeCommit":{"oid":"deadbeef1234567"}}
EOF
  run _run_codify 42 deadbeef1234567
  [[ "$status" -eq 0 ]]
  grep -q 'First line only.' "$LESSONS"
  ! grep -q 'continuation should be ignored' "$LESSONS"
}

@test "lowercase 'codified-learning' is not matched" {
  cat >"$PR_JSON" <<'EOF'
{"commits":[{"messageBody":"x\n\ncodified-learning: lowercase key."}],"mergeCommit":{"oid":"deadbeef1234567"}}
EOF
  before="$(cat "$LESSONS")"
  run _run_codify 42 deadbeef1234567
  [[ "$status" -eq 0 ]]
  [[ "$(cat "$LESSONS")" == "$before" ]]
}
