"""
Codify Codified-Learning trailers from a merged PR into design/lessons.md.

Reads a JSON payload describing the merged PR's commits (from
`gh pr view <N> --json commits,mergeCommit`), extracts every
`Codified-Learning:` trailer, appends one numbered entry per trailer to
`design/lessons.md`, regenerates the auto-generated tag index, and prints
the assigned ID range (e.g. `L-001` or `L-001-L-003`) on stdout for the
calling workflow to use in the codify PR title/branch.

Trailer syntax:

    Codified-Learning: <text>                  -> tag = "general"
    Codified-Learning(do-not-repeat): <text>   -> tag = "do-not-repeat"

The optional `(tag)` segment is a hint for grouping in the index; it can be
anything alphanumeric, dashes, or underscores. Untagged trailers fall under "general".

Output entry format (minimal - the seed L-000 entry shows the richer
hand-authored shape; auto-codified entries are one paragraph + provenance):

    ## L-NNN - YYYY-MM-DD - <tag>

    **Source:** PR #<N> (`<short-sha>`)

    <trailer text>

    ---

# :example
gh pr view 42 --json commits,mergeCommit | \
    python3 -m tests.hooks.codify_learnings \
    --pr 42 --merge-sha $(git rev-parse HEAD)
"""

import argparse
import json
import os
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(
    os.environ.get("CODIFY_REPO_ROOT") or Path(__file__).resolve().parents[2]
)

TRAILER_RE = re.compile(
    r"^Codified-Learning(?:\(([a-zA-Z0-9_-]+)\))?:\s+(\S.*)$",
    re.MULTILINE,
)
LESSON_HEADING_RE = re.compile(
    r"^## L-(\d+) - (\d{4}-\d{2}-\d{2}) - (\S[^\n]*?)\s*$",
    re.MULTILINE,
)

INDEX_BEGIN = "<!-- AUTO-GENERATED by codify_learnings.py - do not edit by hand -->"
INDEX_END = "<!-- /AUTO-GENERATED -->"
INDEX_PATTERN = re.compile(
    re.escape(INDEX_BEGIN) + r".*?" + re.escape(INDEX_END),
    re.DOTALL,
)


def parse_trailers(commit_msgs: list[str]) -> list[tuple[str, str]]:
    """Yield (tag, text) per Codified-Learning trailer across all messages."""
    out: list[tuple[str, str]] = []
    for msg in commit_msgs:
        for m in TRAILER_RE.finditer(msg or ""):
            tag = (m.group(1) or "general").strip()
            text = m.group(2).strip()
            out.append((tag, text))
    return out


def next_lesson_id(lessons_md: str) -> int:
    """Return highest existing L-NNN + 1, or 1 if none yet."""
    ids = [int(m.group(1)) for m in LESSON_HEADING_RE.finditer(lessons_md)]
    return (max(ids) + 1) if ids else 1


def format_entry(
    lesson_id: int, today: str, tag: str, text: str, pr_num: int, short_sha: str
) -> str:
    """Render one Markdown entry block."""
    return (
        f"## L-{lesson_id:03d} - {today} - {tag}\n\n"
        f"**Source:** PR #{pr_num} (`{short_sha}`)\n\n"
        f"{text}\n\n"
        "---\n"
    )


def _heading_anchor(lesson_id: int, date: str, tag: str) -> str:
    # GitHub auto-anchor for "## L-NNN - YYYY-MM-DD - tag": lowercase, spaces
    # become dashes, all chars in the entry are already anchor-safe (digits,
    # ASCII letters, hyphens, underscores from trailer regex [a-zA-Z0-9_-]).
    return f"l-{lesson_id:03d}---{date}---{tag.lower()}"


def regenerate_index(lessons_md: str) -> str:
    """Replace the body between INDEX_BEGIN/INDEX_END with tag -> ID list."""
    tag_to_entries: dict[str, list[tuple[int, str]]] = {}
    for m in LESSON_HEADING_RE.finditer(lessons_md):
        lesson_id = int(m.group(1))
        date = m.group(2)
        tag = m.group(3).strip()
        tag_to_entries.setdefault(tag, []).append((lesson_id, date))

    if not tag_to_entries:
        body = (
            "_(none yet - first entry will land here after the first PR "
            "with a `Codified-Learning:` trailer merges)_"
        )
    else:
        lines = []
        for tag in sorted(tag_to_entries):
            entries = sorted(tag_to_entries[tag])
            id_links = ", ".join(
                f"[L-{i:03d}](#{_heading_anchor(i, d, tag)})" for i, d in entries
            )
            lines.append(f"- **{tag}** - {id_links}")
        body = "\n".join(lines)

    replacement = (
        f"{INDEX_BEGIN}\n"
        "<!-- Tags populate as entries land via the post-merge workflow -->\n\n"
        f"{body}\n\n"
        f"{INDEX_END}"
    )
    return INDEX_PATTERN.sub(replacement, lessons_md)


def _load_commits(input_path: str) -> list[str]:
    """Read JSON from stdin ('-') or file, return list of commit messageBodies."""
    if input_path == "-":
        data = json.load(sys.stdin)
    else:
        data = json.loads(Path(input_path).read_text())
    return [c.get("messageBody", "") for c in data.get("commits", [])]


def main(argv: list[str]) -> int:
    """Codify trailers from a merged PR into design/lessons.md."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--pr", type=int, required=True, help="PR number")
    parser.add_argument("--merge-sha", required=True, help="Merge commit SHA")
    parser.add_argument(
        "--lessons-md",
        default=str(REPO_ROOT / "design" / "lessons.md"),
        help="Path to lessons ledger (default: design/lessons.md under REPO_ROOT)",
    )
    parser.add_argument(
        "--input",
        default="-",
        help="JSON file with commits (default: '-' = stdin)",
    )
    args = parser.parse_args(argv)

    commit_msgs = _load_commits(args.input)
    trailers = parse_trailers(commit_msgs)
    if not trailers:
        print("No Codified-Learning trailers found; nothing to do.", file=sys.stderr)
        return 0

    lessons_path = Path(args.lessons_md)
    lessons_md = lessons_path.read_text()

    next_id = next_lesson_id(lessons_md)
    today = date.today().isoformat()
    short_sha = args.merge_sha[:7]

    appended: list[int] = []
    for tag, text in trailers:
        entry = format_entry(next_id, today, tag, text, args.pr, short_sha)
        lessons_md = lessons_md.rstrip() + "\n\n" + entry
        appended.append(next_id)
        next_id += 1

    lessons_md = regenerate_index(lessons_md)
    if not lessons_md.endswith("\n"):
        lessons_md += "\n"
    lessons_path.write_text(lessons_md)

    first, last = appended[0], appended[-1]
    print(f"L-{first:03d}" if first == last else f"L-{first:03d}-L-{last:03d}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
