#!/usr/bin/env bash
: '
# :build the env with every scope enabled and verify the declared bins
tests/nix/build_scope_env.sh

# :build a subset of scopes
tests/nix/build_scope_env.sh --scopes "shell python k8s_base k8s_ext"

# :build for another platform (needs a builder for that system)
tests/nix/build_scope_env.sh --system aarch64-darwin

# :keep the generated flake directory for inspection
tests/nix/build_scope_env.sh --keep
'
# Builds nix/flake.nix with a generated config.nix, then asserts that every
# binary declared in a scope's `# bins:` comment exists in the result.
#
# The build itself is the collision test: pkgs.buildEnv fails hard when two
# packages ship the same relative path (e.g. minikube's bin/kubectl symlink vs
# the real kubectl), and no per-scope CI job can catch that - only a run with
# all scopes enabled at once puts the conflicting packages in the same env.
set -eo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCOPES_JSON="$REPO_ROOT/.assets/lib/scopes.json"
SCOPES_DIR="$REPO_ROOT/nix/scopes"

# Bins whose owning package must be pinned - a `# bins:` presence check alone
# passes even when the wrong package wins a buildEnv collision. Format:
# "<bin>:<substring the resolved store path must contain>".
BIN_OWNERS="kubectl:-kubectl-"

scopes=""
system=""
keep=false

_need_value() {
  [ $# -ge 2 ] || {
    printf '\e[31;1m%s requires a value\e[0m\n' "$1" >&2
    exit 1
  }
}

while [ $# -gt 0 ]; do
  case "$1" in
  --scopes)
    _need_value "$@"
    scopes="$2"
    shift 2
    ;;
  --system)
    _need_value "$@"
    system="$2"
    shift 2
    ;;
  --keep)
    keep=true
    shift
    ;;
  -h | --help)
    # Print the examples block without its `: '` delimiters.
    sed -n "/^: '/,/^'$/p" "${BASH_SOURCE[0]}" | sed '1d;$d'
    exit 0
    ;;
  *)
    printf '\e[31;1munknown argument: %s\e[0m\n' "$1" >&2
    exit 1
    ;;
  esac
done

command -v nix >/dev/null 2>&1 || {
  printf '\e[31;1mnix not found - install Nix first.\e[0m\n' >&2
  exit 1
}

# Follow a symlink chain to its final target. `readlink -f` is GNU-only and
# this script also runs on macOS runners (see decision 0009).
_resolve_link() {
  local path="$1" hops=0 target
  while [ -L "$path" ] && [ "$hops" -lt 16 ]; do
    target="$(readlink "$path")"
    case "$target" in
    /*) path="$target" ;;
    *) path="$(dirname "$path")/$target" ;;
    esac
    hops=$((hops + 1))
  done
  printf '%s\n' "$path"
}

if [ -z "$scopes" ]; then
  # Value lines only - the `"valid_scopes": [` header is excluded by anchoring
  # the quoted name to the end of the line.
  scopes="$(sed -n '/"valid_scopes"/,/]/p' "$SCOPES_JSON" |
    sed -n 's/^ *"\([a-z0-9_]*\)",\{0,1\}$/\1/p' | tr '\n' ' ')"
fi
[ -n "$scopes" ] || {
  printf '\e[31;1mno scopes resolved from %s\e[0m\n' "$SCOPES_JSON" >&2
  exit 1
}

# Fail on a scope with no `.nix` file rather than skipping it later: the flake
# treats a missing scope file as empty, so an unknown name (a typo in --scopes,
# or drift between scopes.json and nix/scopes/) would otherwise build a smaller
# env than asked for and still report PASSED.
for sc in $scopes; do
  [ -f "$SCOPES_DIR/$sc.nix" ] || {
    printf '\e[31;1munknown scope "%s" - no %s/%s.nix\e[0m\n' "$sc" "$SCOPES_DIR" "$sc" >&2
    exit 1
  }
done

if [ -z "$system" ]; then
  system="$(nix eval --impure --raw --expr builtins.currentSystem)"
fi

work_dir="$(mktemp -d "${TMPDIR:-/tmp}/scope-env.XXXXXX")"
$keep || trap 'rm -rf "$work_dir"' EXIT

cp -R "$REPO_ROOT/nix/." "$work_dir/"
{
  printf '# Generated by tests/nix/build_scope_env.sh -- do not commit.\n{\n'
  # isInit mirrors a host without system curl/jq (the widest package set);
  # allowUnfree keeps unfree-gated packages (terraform) in the build.
  printf '  isInit = true;\n  allowUnfree = true;\n\n  scopes = [\n'
  for sc in $scopes; do printf '    "%s"\n' "$sc"; done
  printf '  ];\n}\n'
} >"$work_dir/config.nix"

printf '\e[96mbuilding dev-env for %s with %s scopes:\e[0m %s\n' "$system" "$(echo $scopes | wc -w | tr -d ' ')" "$scopes"

out_path="$(nix build "path:$work_dir#packages.$system.default" --no-link --print-out-paths)" || {
  printf '\e[31;1mbuild failed - see the buildEnv error above (package collision or eval error).\e[0m\n' >&2
  exit 1
}
printf '\e[32mbuilt:\e[0m %s\n\n' "$out_path"

failed=0
for sc in $scopes; do
  bins="$(sed -n 's/^# bins: *//p' "$SCOPES_DIR/$sc.nix")" || true
  for bin in $bins; do
    # `(external-installer)` marks a scope whose tooling is installed outside
    # nix; a `%` suffix marks a binary provided by a manager (fnm, tfswitch)
    # rather than the nix profile. Neither lands in the built env.
    case "$bin" in
    '(external-installer)' | *%) continue ;;
    esac
    if [ ! -e "$out_path/bin/$bin" ]; then
      printf '\e[31m%-14s %-24s MISSING\e[0m\n' "$sc" "$bin"
      failed=1
      continue
    fi
    owner=""
    for entry in $BIN_OWNERS; do
      case "$entry" in
      "$bin":*) owner="${entry#*:}" ;;
      esac
    done
    if [ -n "$owner" ]; then
      target="$(_resolve_link "$out_path/bin/$bin")"
      case "$target" in
      *"$owner"*) ;;
      *)
        printf '\e[31m%-14s %-24s resolves to %s (expected a path matching %s)\e[0m\n' \
          "$sc" "$bin" "$target" "$owner"
        failed=1
        continue
        ;;
      esac
    fi
    printf '\e[32m%-14s %-24s ok\e[0m\n' "$sc" "$bin"
  done
done

if [ "$failed" -ne 0 ]; then
  printf '\n\e[31;1m>> scope env check FAILED\e[0m\n' >&2
  exit 1
fi
printf '\n\e[32;1m>> scope env check PASSED\e[0m\n'
